MACHINE: mortimer             # Processing HPC, can be bash, shao, or ozstar 
TIMESTEP: 300             # Short image timestep, unit of seconds, if gives 'int' it is the integration time
SURVEY: other               # emu, vast, other
CASA: casa                # path or shortcut to call casa 
EMAIL: raghav@uwm.edu     #email id for job start and completion notification

CONDA: /raid-15/LS/kaplan/raghav/VAST/software/.activate_conda  # conda source file in HPC
CONDAENV: vaster    # conda virtual environment name
CASAPATH: /raid-15/LS/kaplan/raghav/VAST/software/.activate_casa # casa source file in HPC

RESETMODEL: False 
MODELCLEAN:
  EMU:
    IMSIZE: 6144
    CELL: '2.5arcsec'
    DATACOLUMN: data
    DECONVOLVER: mtmfs
    NTERM: 2
    SCALES: [0, 10, 30]
    NITER: 10000
    WEIGHTING: briggs     # natural, uniform, briggs
    ROBUST: 0.5
    UVRANGE: '>200m'
    PBCOR: False
    PBLIMIT: -0.2
    GAIN: 0.2
    THRESHOLD: 0.0 
    GRIDDER: widefield
    FACETS: 2
    WPROJPLANES: -1
    SAVEMODEL: modelcolumn
    TIMERANGE: ''
    STOKES: I 

  VAST:
    IMSIZE: 6144
    CELL: '2.5arcsec'
    DATACOLUMN: data
    DECONVOLVER: "mtmfs"
    NTERM: 2
    SCALES: [0, 10, 30]
    NITER: 5000
    WEIGHTING: briggs     # natural, uniform, briggs
    ROBUST: 0.5
    UVRANGE: '>200m'
    PBCOR: False
    PBLIMIT: -0.2
    GAIN: 0.2
    THRESHOLD: 0.75mJy
    GRIDDER: widefield
    FACETS: 2
    WPROJPLANES: -1
    SAVEMODEL: modelcolumn
    TIMERANGE: ''
    STOKES: I 

  OTHER:
    IMSIZE: 6144
    CELL: '2.5arcsec'
    DATACOLUMN: 'data'
    DECONVOLVER: 'mtmfs'
    NTERM: 2
    SCALES: [0, 10, 30]
    NITER: 10000
    WEIGHTING: 'briggs'     # natural, uniform, briggs
    ROBUST: 0.5
    UVRANGE: '>200m'
    PBCOR: False
    PBLIMIT: -0.2
    GAIN: 0.2
    THRESHOLD: 0.0 
    GRIDDER: 'widefield'
    FACETS: 2
    WPROJPLANES: -1
    SAVEMODEL: 'modelcolumn'
    TIMERANGE: ''
    STOKES: I 


CAL: True                 # run self cal or not 
SELFCAL:
  UVRANGE: '>200m'
  SOLINT: 1min              # int or 1min
  CALMODE: p              # p for phase, a for amplitude 


SHORTIMAGE:
  IMSIZE: 2880
  CELL: ['2.5arcsec']
  DATACOLUMN: corrected
  DECONVOLVER: multiscale
  NTERM: 1
  SCALES: [0]
  NITER: 0
  WEIGHTING: briggs       # natural, uniform, briggs
  ROBUST: 0.5
  UVRANGE: '>200m'
  PBCOR: False
  PBLIMIT: -0.2
  GAIN: 0.1
  THRESHOLD: 0.0 
  GRIDDER: 'widefield'
  FACETS: 2
  WPROJPLANES: -1
  SAVEMODEL: none
  STOKES: I 


CANDIDATES:
  KTYPE: ['chisquare', 'peak', 'std'] 
  MAP: ['chisquare', 'peak']
  THRESHOLD_SIMGA:
    CHISQUARE: 6
    PEAK: 6
    GAUSSIAN: 6
  LOG_THRESHOLD_SIGMA:
    CHISQUARE: 5
    PEAK: 5
    GAUSSIAN: 6
  MIN_DISTANCE: 30
  SAVEVOT: False
  GAUSSIAN_WIDTH: 4
    

OZSTAR:
  FIXDATA:
    TIME: '1:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 4gb  # VAST 0GB max  
  MODELING:
    TIME: '50:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 16gb  # VAST 11GB max 
  IMGFAST:
    TIME: '30:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 4gb  # VAST 1.2GB max
  SELCAND:
    TIME: '10:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 32gb  # VAST 16GB max (70 images)
  CLNDATA:
    TIME: '1:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 200mb  # VAST 0GB max

MORTIMER:
  FIXDATA:
    TIME: '1:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 4gb  # VAST 0GB max  
  MODELING:
    TIME: '50:00:00'
    NODES: 1
    NTASKS: 17
    PARTITION: highmem
    MEM: 16gb  # VAST 11GB max
  MODELING_PARALLEL:
    TIME: '50:00:00'
    NODES: 1
    NTASKS: 17
    PARTITION: highmem
    MEM: 16gb  # VAST 11GB max 
  IMGFAST:
    TIME: '30:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 4gb  # VAST 1.2GB max
  SELCAND:
    TIME: '10:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 32gb  # VAST 16GB max (70 images)
  CLNDATA:
    TIME: '1:00:00'
    NODES: 1
    NTASKS: 1
    MEM: 200mb  # VAST 0GB max
